version: '2'

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5490:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: hackme
      POSTGRES_DB: cv_table
