"""Init db.

Revision ID: baa6fc1fa128
Revises: 
Create Date: 2021-01-12 21:04:53.280407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('skill_weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__skills'))
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('visit_datetime', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('cookie_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__visits'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('skills')
    # ### end Alembic commands ###
